### ISSUE TITLE
can not upload media file

### ISSUE THREAD

**Issue by different-thinking** [podlove/podlove-publisher#1422]
maybe same issue as:  #1420 

I don't find the field for uploading my media file any longer:
![image](https://github.com/podlove/podlove-publisher/assets/10116611/1f03f3a4-23e4-45c7-8bca-acec9a36fdea)

![image](https://github.com/podlove/podlove-publisher/assets/10116611/76886689-16db-4795-810f-24fd12765673)

In Edge I'm getting a couple of errors:

Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at HTMLDocument.podloveInitShowWidgetNumberingHook (post.php?post=9592&action=edit&classic-editor:1470:36)
load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.4.2:2  

TypeError: Cannot read properties of undefined (reading 'getEditedPostAttribute')
    at LM (client.js:52:3951)
    at LM.next (<anonymous>)
    at v (client.js:22:1351)
    at Qc (client.js:22:1173)
    at client.js:19:9384
    at ix (client.js:19:6348)
    at sN (client.js:19:9364)
    at y (client.js:22:1599)
    at w (client.js:22:2032)
    at v (client.js:22:1413)
kL @ client.js:19
client.js:19  

The above error occurred in task LM
    created by takeEvery(channel, LM)
    created by RM
    created by anonymous
    created by anonymous
    created by anonymous
Tasks cancelled due to error:
takeEvery(channel, LM)
takeEvery(channel, NM)
takeEvery(podlove/publisher/wordpress/SELECT_MEDIA_FROM_LIBRARY, DM)

Same issue in Firefox but without any errors.

`Website                    https://different-thinking.de/blog
PHP Version                8.2.9
WordPress Version          6.4.2
WordPress Theme            Focusblog Child v2.0.0
Active Plugins             
           - Add Tags And Category To Page And Post Types v2.3
           - Admin Menu Editor Pro v2.22.1
           - Antispam Bee v2.11.5
           - Blog2Social: Social Media Auto Post & Scheduler v7.3.4
           - Broken Link Checker v2.2.3
           - Classic Editor v1.6.3
           - WP OPcache v4.2.0
           - OMGF Pro v3.10.1
           - OMGF v5.7.6
           - Image Source Control v2.8.0
           - Imagify v2.1.3
           - Internal Link Juicer (Pro) v2.23.4
           - Kali Forms Google Sheets v1.0.3
           - Kali Forms Pro v1.8.14
           - Kali Forms Submissions v1.5.0
           - Kali Forms WebHooks v1.1.4
           - Kali Forms - WordPress Forms Made Easy v2.3.29
           - MainWP Child v4.5.3
           - Page Excerpt v1.3
           - Podlove Podcast Publisher v4.0.9
           - Podlove Web Player v5.7.3
           - Post SMTP v2.8.6
           - Search Exclude v2.0.6
           - Rank Math SEO PRO v3.0.51
           - Sucuri Security - Auditing, Malware Scanner and Hardening v1.8.39
           - Table of Contents Plus v2311
           - Thrive Clever Widgets v1.56.1
           - Thrive Intercom Beta v0.1
           - Thrive Leads v3.25
           - Thrive Ovation v3.23
           - Thrive Product Manager v1.17
           - Thrive Architect v3.27
           - Advanced Editor Tools v5.9.2
           - Two Factor Authentication v1.14.17
           - UpdraftPlus - Backup/Restore v2.23.14.26
           - Patchstack v2.0.20
           - WordPress Hide Posts v1.1.1
           - WP-WebAuthn v1.3.1
           - Worthy - VG WORT Integration für Wordpress v1.7.0-0cde1c2
           - WPFront Scroll Top v2.2
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          4.0.9
Publisher Database Version 153
Web Player Version         player_v5
open_basedir               ok
curl Version               7.68.0
iconv                      available
simplexml                  ok
max_execution_time         30
upload_max_filesize        200M
memory_limit               640M
disable_classes            
disable_functions          
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - m4a    audio/mp4        https://different-thinking.de/feed/itmp-mp4/
  - mp3    audio/mpeg       https://different-thinking.de/feed/itmp-mp3/
cron                       ok
duplicate_guids            ok

0 errors
0 notices
Nice, Everything looks fine!`

PHP Debug:
`Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Enclosure::$interoperability is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-enclosure.php on line 31

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Block::$interoperability is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/block/class-podlove-web-player-block.php on line 70

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Block::$interoperability is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/block/class-podlove-web-player-block.php on line 70

Deprecated: Creation of dynamic property Webarx::$uploads is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/webarx/webarx.php on line 195

Notice: Function is_category was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/htdocs/rsieber/blog/wp-includes/functions.php on line 6031

Notice: Function is_tag was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/htdocs/rsieber/blog/wp-includes/functions.php on line 6031

Notice: Function is_home was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/htdocs/rsieber/blog/wp-includes/functions.php on line 6031

Deprecated: Creation of dynamic property KaliForms\Inc\Utils\EmailUtilities\Email_Logger::$mailer is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/kali-forms/Inc/Utils/EmailUtilities/class-email-logger.php on line 43

Notice: Function is_category was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/htdocs/rsieber/blog/wp-includes/functions.php on line 6031

Notice: Function is_tag was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/htdocs/rsieber/blog/wp-includes/functions.php on line 6031

Notice: Function is_home was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/htdocs/rsieber/blog/wp-includes/functions.php on line 6031

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /www/htdocs/rsieber/blog/wp-includes/functions.php on line 7241

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /www/htdocs/rsieber/blog/wp-includes/functions.php on line 2187

Deprecated: Function utf8_encode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 62

Deprecated: Function utf8_encode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 62

Deprecated: Function utf8_encode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 62

Deprecated: Function utf8_encode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 62

Deprecated: Function utf8_encode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 63

Deprecated: Function utf8_encode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 63

Deprecated: Function utf8_encode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 63

Deprecated: Function utf8_encode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 63

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Embed_API::$options is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-embed-api.php on line 56

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Embed_API::$options is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-embed-api.php on line 56

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultConfig is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 48

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTheme is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 49

Deprecated: Creation of dynamic property Podlove_Web_Player_Options::$defaultTemplate is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-options.php on line 50

Deprecated: Creation of dynamic property Podlove_Web_Player_Embed_API::$options is deprecated in /www/htdocs/rsieber/blog/wp-content/plugins/podlove-web-player/includes/class-podlove-web-player-embed-api.php on line 56

Deprecated: Function utf8_decode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 93

Deprecated: Function utf8_decode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 93

Deprecated: Function utf8_decode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 93

Deprecated: Function utf8_decode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 93

Deprecated: Function utf8_decode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 93

Deprecated: Function utf8_decode() is deprecated in /www/htdocs/rsieber/blog/wp-content/languages/de_DE.php on line 93`

**Comment by eteubert** [comment]
If you have the Publisher setup to manually upload files to WordPress, there should be a button in the Media Files section:

![Screenhot Firefox Developer Edition 2023-12-26 20 19 08@2x](https://github.com/podlove/podlove-publisher/assets/235918/5efea3a4-2047-4eee-a29e-2f3a3bb1b830)


> In Edge I'm getting a couple of errors:

> Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
> at HTMLDocument.podloveInitShowWidgetNumberingHook

Try disabling the "automatic numbering" module, it currently has issues.

The PHP logs don't seem related / critical.

**Comment by different-thinking** [comment]
There is no button:

![image](https://github.com/podlove/podlove-publisher/assets/10116611/5ba49d50-2147-4f36-b6fc-b9eacf68b83f)

**Comment by different-thinking** [comment]
Oh, I see I need to activate:
![image](https://github.com/podlove/podlove-publisher/assets/10116611/964b18c4-48cf-41cd-beed-847b79346a0d)

When does that changed?

**Comment by different-thinking** [comment]
Nope, not working. When clicking the upload button nothing happens. When loading the site I get the following errors:

![image](https://github.com/podlove/podlove-publisher/assets/10116611/e9dd80f4-3e2d-49b4-99e8-4a475501b12c)
[different-thinking.de-1704439004692.log](https://github.com/podlove/podlove-publisher/files/13839190/different-thinking.de-1704439004692.log)

Settings:
![image](https://github.com/podlove/podlove-publisher/assets/10116611/70b66c4e-55fc-4284-b28d-5a672cc6eb56)

Directory exists:
![image](https://github.com/podlove/podlove-publisher/assets/10116611/cb49b9a6-df8c-4474-85c3-379a187337a0)

**Comment by eteubert** [comment]
This module was always necessary for direct upload.

Is this issue resolved?
